import {
  Controller,
  Get,
  Post,
  Param,
  Body,
  Query,
  Res,
  UseGuards,
  ForbiddenException,
  NotFoundException,
} from '@nestjs/common';
import { Response } from 'express';
import { ApiTags, ApiBearerAuth } from '@nestjs/swagger';
import * as fs from 'fs';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { ReportsService, ReportFormat } from './reports.service';
import { SurveysService } from '../surveys/surveys.service';
import { MailEventsService } from '../mail/mail-events.service';
import { AuditService } from '../audit/audit.service';
import { RealtimeGateway } from '../realtime/realtime.gateway';

const MIME: Record<ReportFormat, string> = {
  PDF: 'application/pdf',
  CSV: 'text/csv',
  JSON: 'application/json',
  GEOJSON: 'application/geo+json',
};

@ApiTags('reports')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard)
@Controller('reports')
export class ReportsController {
  constructor(
    private reportsService: ReportsService,
    private surveysService: SurveysService,
    private mailEvents: MailEventsService,
    private auditService: AuditService,
    private realtime: RealtimeGateway,
  ) {}

  @Post('surveys/:surveyId/generate')
  async generate(
    @CurrentUser() user: any,
    @Param('surveyId') surveyId: string,
    @Body('format') format: ReportFormat = 'PDF',
  ) {
    if (user.role === 'OPERATOR' && user.operatorPermissions?.canGenerateReports === false) {
      throw new ForbiddenException({
        success: false,
        error: { code: 'INSUFFICIENT_PERMISSIONS', message: 'You do not have permission to generate reports.' },
      });
    }
    const survey = await this.surveysService.findById(surveyId);
    if (user.role === 'OPERATOR' && !this.surveysService.isOperatorAssigned(survey as any, user.userId)) {
      throw new ForbiddenException({
        success: false,
        error: { code: 'NOT_ASSIGNED', message: 'You are not assigned to this survey.' },
      });
    }

    const report = await this.reportsService.generate(surveyId, format, user.userId);

    this.realtime.emitEvent('report_generated', {
      reportId: report._id,
      surveyId,
      format,
      detectionCount: report.detectionCount,
    });

    await this.auditService.record({
      userId: user.userId,
      userEmail: user.email,
      userRole: user.role,
      action: 'REPORT_GENERATED',
      category: 'REPORTS',
      targetType: 'Report',
      targetId: String(report._id),
      metadata: { surveyId, format, detectionCount: report.detectionCount },
    });

    await this.mailEvents.dispatch(
      'REPORT_GENERATED',
      `Survey report generated: ${survey.code} (${format})`,
      `<div style="font-family:sans-serif"><h3>Survey report generated</h3><p>Survey <b>${survey.name}</b> (${survey.code}) - ${format} report with ${report.detectionCount} detection(s) generated by ${user.email}.</p></div>`,
      `Survey report generated: ${survey.name} (${survey.code}) - ${format} - ${report.detectionCount} detections.`,
      { surveyId, reportId: String(report._id), format, severity: 'INFO' },
    );

    return { success: true, data: report };
  }

  @Get()
  async list(@Query('page') page = '1', @Query('limit') limit = '30', @Query('surveyId') surveyId?: string) {
    const filter: Record<string, any> = {};
    if (surveyId) filter.surveyId = surveyId;
    const { items, total } = await this.reportsService.findAll(parseInt(page, 10), parseInt(limit, 10), filter);
    return { success: true, data: items, meta: { total, page: parseInt(page, 10), limit: parseInt(limit, 10) } };
  }

  @Get(':id/download')
  async download(@Param('id') id: string, @Res() res: Response) {
    const report = await this.reportsService.findById(id);
    if (!report) {
      throw new NotFoundException({ success: false, error: { code: 'REPORT_NOT_FOUND', message: 'Report not found.' } });
    }
    const absolutePath = this.reportsService.getAbsolutePath(report.storagePath);
    if (!fs.existsSync(absolutePath)) {
      throw new NotFoundException({ success: false, error: { code: 'REPORT_FILE_MISSING', message: 'Report file is missing on disk.' } });
    }
    res.setHeader('Content-Type', MIME[report.format as ReportFormat] || 'application/octet-stream');
    res.setHeader('Content-Disposition', `attachment; filename="${report.fileName}"`);
    fs.createReadStream(absolutePath).pipe(res);
  }

  @Post(':id/email')
  async emailReport(@CurrentUser() user: any, @Param('id') id: string, @Body('recipientEmails') recipientEmails?: string[]) {
    const report = await this.reportsService.findById(id);
    if (!report) {
      throw new NotFoundException({ success: false, error: { code: 'REPORT_NOT_FOUND', message: 'Report not found.' } });
    }

    const absolutePath = this.reportsService.getAbsolutePath(report.storagePath);
    const targetRecipients = recipientEmails && recipientEmails.length > 0 
      ? recipientEmails 
      : [user.email, 'asonawane260686@gmail.com'];

    await this.mailEvents.dispatch(
      'REPORT_GENERATED',
      `MarineVision AI: Official Survey Report ${report.surveyCode} (${report.format})`,
      `<div style="font-family:sans-serif;max-width:600px;margin:auto;padding:20px;border:1px solid #0e7490;border-radius:8px">
        <h2 style="color:#0e7490">MarineVision AI — Survey Mission Report</h2>
        <p>Official report for survey <b>${report.surveyCode}</b> has been generated in format <b>${report.format}</b>.</p>
        <p>Total Detections Logged: <b>${report.detectionCount}</b></p>
        <p>Requested by: <b>${user.email}</b></p>
        <p>Attached: <b>${report.fileName}</b></p>
      </div>`,
      `Official report for survey ${report.surveyCode} (${report.format}) with ${report.detectionCount} detections. Requested by ${user.email}.`,
      {
        reportId: String(report._id),
        reportPath: absolutePath,
        fileName: report.fileName,
        recipientEmails: targetRecipients,
        manualSend: true,
        severity: 'INFO',
      },
    );

    await this.reportsService.markEmailed(id, targetRecipients);

    await this.auditService.record({
      userId: user.userId,
      userEmail: user.email,
      userRole: user.role,
      action: 'REPORT_EMAILED',
      category: 'REPORTS',
      targetType: 'Report',
      targetId: id,
      metadata: { recipientEmails: recipientEmails || [] },
    });

    return { success: true, data: { queued: true } };
  }
}
