export const historicalData = [
  {
    "sourceId": "NOAA-TITANIC-2004-EXPEDITION",
    "name": "RMS Titanic wreck reference",
    "type": "SHIPWRECK",
    "eventYear": 2004,
    "eventDate": "2004-05-27",
    "latitude": 41.7325,
    "longitude": -49.94695,
    "depthMeters": 3840,
    "quantity": 1,
    "description": "NOAA Titanic expedition reference; heritage/wreck point, not a current AI detection.",
    "sourceOrganization": "NOAA Ocean Exploration / NOAA NCEI",
    "sourceUrl": "https://repository.library.noaa.gov/view/noaa/10519/noaa_10519_DS1.pdf",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "titanic",
      "wreck",
      "heritage"
    ]
  },
  {
    "sourceId": "NOAA-MAERSK-ESSEN-2021",
    "name": "M/V Maersk Essen lost containers",
    "type": "CONTAINER",
    "eventYear": 2021,
    "eventDate": "2021-01-16",
    "latitude": 28.411667,
    "longitude": -154.126667,
    "depthMeters": null,
    "quantity": 732,
    "description": "Approximate incident position for an estimated 732 lost 40-foot containers.",
    "sourceOrganization": "NOAA IncidentNews / USCG",
    "sourceUrl": "https://incidentnews.noaa.gov/incident/10221",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "2021",
      "containers",
      "marine-debris"
    ]
  },
  {
    "sourceId": "NOAA-WASHINGTON-CONTAINERS-2021",
    "name": "Washington Coast container-loss incident",
    "type": "CONTAINER",
    "eventYear": 2021,
    "eventDate": "2021-10-21",
    "latitude": 48.3385,
    "longitude": -123.360667,
    "depthMeters": null,
    "quantity": 110,
    "description": "NOAA incident reference for approximately 110 containers reported overboard.",
    "sourceOrganization": "NOAA IncidentNews / USCG",
    "sourceUrl": "https://incidentnews.noaa.gov/incident/10374",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "2021",
      "containers",
      "marine-debris"
    ]
  },
  {
    "sourceId": "NOAA-TOURIST2-2022",
    "name": "M/V Tourist No. 2 partially sunk",
    "type": "SHIPWRECK",
    "eventYear": 2022,
    "eventDate": "2022-07-28",
    "latitude": 46.192,
    "longitude": -123.836667,
    "depthMeters": null,
    "quantity": 1,
    "description": "Partially sunk 1924 former car ferry and derelict vessel reference in Astoria.",
    "sourceOrganization": "NOAA IncidentNews / USCG",
    "sourceUrl": "https://incidentnews.noaa.gov/incident/10496",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "2022",
      "shipwreck",
      "derelict-vessel"
    ]
  },
  {
    "sourceId": "NOAA-MATADOR-2023",
    "name": "F/V Matador sunken vessel",
    "type": "SHIPWRECK",
    "eventYear": 2023,
    "eventDate": "2023-02-08",
    "latitude": 33.845833,
    "longitude": -118.415,
    "depthMeters": 51.8,
    "quantity": 1,
    "description": "43-foot fishing vessel reported sunk about one-third mile offshore of Redondo Beach.",
    "sourceOrganization": "NOAA IncidentNews / USCG",
    "sourceUrl": "https://incidentnews.noaa.gov/incident/10567",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "2023",
      "shipwreck",
      "sunken-vessel"
    ]
  },
  {
    "sourceId": "NOAA-MAZAPETA-2023",
    "name": "Tug MAZAPETA sunken vessel",
    "type": "SHIPWRECK",
    "eventYear": 2023,
    "eventDate": "2023-09-04",
    "latitude": 38.057333,
    "longitude": -121.501,
    "depthMeters": null,
    "quantity": 1,
    "description": "Sunken tug reference in Little Potato Slough, Stockton, California.",
    "sourceOrganization": "NOAA IncidentNews / USCG",
    "sourceUrl": "https://incidentnews.noaa.gov/incident/10669",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "2023",
      "shipwreck",
      "derelict-vessel"
    ]
  },
  {
    "sourceId": "NOAA-PRESIDENT-EISENHOWER-2024",
    "name": "M/V President Eisenhower lost containers",
    "type": "CONTAINER",
    "eventYear": 2024,
    "eventDate": "2024-02-07",
    "latitude": 36.283333,
    "longitude": -122.973333,
    "depthMeters": null,
    "quantity": 24,
    "description": "NOAA reported 24 containers lost offshore of Monterey; approximate incident coordinates.",
    "sourceOrganization": "NOAA IncidentNews / USCG",
    "sourceUrl": "https://incidentnews.noaa.gov/incident/10740",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "2024",
      "containers",
      "marine-debris"
    ]
  },
  {
    "sourceId": "NOAA-DALI-2024",
    "name": "DALI / Key Bridge marine-casualty reference",
    "type": "MARINE_DEBRIS",
    "eventYear": 2024,
    "eventDate": "2024-03-26",
    "latitude": 39.270333,
    "longitude": -76.574667,
    "depthMeters": null,
    "quantity": null,
    "description": "NOAA incident reference notes containers fell into the water after the vessel struck the Francis Scott Key Bridge.",
    "sourceOrganization": "NOAA IncidentNews / USCG",
    "sourceUrl": "https://incidentnews.noaa.gov/incident/10761",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "2024",
      "marine-debris",
      "containers",
      "casualty"
    ]
  },
  {
    "sourceId": "NOAA-SM-PORTLAND-2025",
    "name": "C/V S.M. Portland lost containers",
    "type": "CONTAINER",
    "eventYear": 2025,
    "eventDate": "2025-03-04",
    "latitude": 53.37,
    "longitude": 175.98,
    "depthMeters": null,
    "quantity": 81,
    "description": "NOAA reported 81 containers lost approximately 30 miles north of Buldir Island; longitude normalized for globe display.",
    "sourceOrganization": "NOAA IncidentNews / USCG",
    "sourceUrl": "https://incidentnews.noaa.gov/incident/10930",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "2025",
      "containers",
      "marine-debris"
    ]
  },
  {
    "sourceId": "NOAA-FISHING-GEAR-REGIONAL-2022",
    "name": "Upper Great Lakes ghost-net regional reference",
    "type": "FISHING_GEAR",
    "eventYear": 2022,
    "eventDate": "2022-01-01",
    "latitude": 46.5,
    "longitude": -87.0,
    "depthMeters": null,
    "quantity": null,
    "description": "Regional reference for NOAA's Upper Great Lakes ghost-net removal program. This coordinate is a regional map anchor, not an exact sonar target.",
    "sourceOrganization": "NOAA Marine Debris Program",
    "sourceUrl": "https://marinedebris.noaa.gov/removal/increasing-efficiency-locating-and-removing-ghost-nets-upper-great-lakes",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": [
      "ghost-net",
      "fishing-gear",
      "regional-reference"
    ]
  },
  {
    "sourceId": "NOAA-ANOM-01-SAN-DELFINO",
    "name": "San Delfino (Tanker wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-04-10",
    "latitude": 35.39779,
    "longitude": -75.11609,
    "depthMeters": 33.5,
    "quantity": 1,
    "description": "ANOM-01: San Delfino. Tanker wreck at 110 ft depth. Sonar evidence: Side-scan sonar survey.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["san-delfino", "tanker-wreck", "anom-01", "side-scan"]
  },
  {
    "sourceId": "NOAA-ANOM-02-FW-ABRAMS",
    "name": "F.W. Abrams (Tanker wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-06-15",
    "latitude": 34.99012,
    "longitude": -75.80100,
    "depthMeters": 25.9,
    "quantity": 1,
    "description": "ANOM-02: F.W. Abrams. Tanker wreck at 85 ft depth. Sonar evidence: Side-scan sonar.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["fw-abrams", "tanker-wreck", "anom-02", "side-scan"]
  },
  {
    "sourceId": "NOAA-ANOM-03-PAPOOSE",
    "name": "Papoose (Tanker wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-03-19",
    "latitude": 35.62599,
    "longitude": -74.89110,
    "depthMeters": 61.0,
    "quantity": 1,
    "description": "ANOM-03: Papoose. Tanker wreck at 200 ft depth. Sonar evidence: Side-scan sonar.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["papoose", "tanker-wreck", "anom-03", "side-scan"]
  },
  {
    "sourceId": "NOAA-ANOM-04-KYZIKES",
    "name": "Kyzikes (Tanker wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1927,
    "eventDate": "1927-12-04",
    "latitude": 36.06464,
    "longitude": -75.66833,
    "depthMeters": 6.1,
    "quantity": 1,
    "description": "ANOM-04: Kyzikes. Tanker wreck at 20 ft depth (shallow water hazard). Sonar evidence: Side-scan sonar.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["kyzikes", "tanker-wreck", "anom-04", "side-scan"]
  },
  {
    "sourceId": "NOAA-ANOM-05-SULOIDE",
    "name": "Suloide (Freighter wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1943,
    "eventDate": "1943-03-26",
    "latitude": 34.54479,
    "longitude": -76.89499,
    "depthMeters": 19.8,
    "quantity": 1,
    "description": "ANOM-05: Suloide. Freighter wreck at 65 ft depth. Sonar evidence: Side-scan + multibeam.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["suloide", "freighter-wreck", "anom-05", "multibeam"]
  },
  {
    "sourceId": "NOAA-ANOM-06-MARORE",
    "name": "Marore (Freighter wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-02-26",
    "latitude": 35.54410,
    "longitude": -75.24941,
    "depthMeters": 39.6,
    "quantity": 1,
    "description": "ANOM-06: Marore. Freighter wreck at 130 ft depth. Sonar evidence: Side-scan sonar.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["marore", "freighter-wreck", "anom-06", "side-scan"]
  },
  {
    "sourceId": "NOAA-ANOM-07-PANAM",
    "name": "Panam (Tanker wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-05-04",
    "latitude": 34.14424,
    "longitude": -76.13006,
    "depthMeters": 146.3,
    "quantity": 1,
    "description": "ANOM-07: Panam. Tanker wreck at 480 ft depth. Sonar evidence: Side-scan sonar.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["panam", "tanker-wreck", "anom-07", "side-scan"]
  },
  {
    "sourceId": "NOAA-ANOM-08-NORVANA",
    "name": "Norvana (Freighter wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-01-19",
    "latitude": 36.06721,
    "longitude": -75.22749,
    "depthMeters": 33.5,
    "quantity": 1,
    "description": "ANOM-08: Norvana. Freighter wreck at 110 ft depth. Sonar evidence: Low-frequency side-scan.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["norvana", "freighter-wreck", "anom-08", "low-frequency-side-scan"]
  },
  {
    "sourceId": "NOAA-ANOM-09-MALCHACE",
    "name": "Malchace (Freighter wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-04-09",
    "latitude": 34.60427,
    "longitude": -75.78703,
    "depthMeters": 62.5,
    "quantity": 1,
    "description": "ANOM-09: Malchace. Freighter wreck at 205 ft depth. Sonar evidence: Multibeam + side-scan.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["malchace", "freighter-wreck", "anom-09", "multibeam"]
  },
  {
    "sourceId": "NOAA-ANOM-10-TAMAULIPAS",
    "name": "Tamaulipas (Tanker wreck / broken sections)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-04-10",
    "latitude": 34.53880,
    "longitude": -76.01559,
    "depthMeters": 47.2,
    "quantity": 1,
    "description": "ANOM-10: Tamaulipas. Tanker wreck / broken sections at 155 ft depth. Sonar evidence: Side-scan + video.",
    "sourceOrganization": "NOAA Maritime Heritage Archive",
    "sourceUrl": "https://sanctuaries.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["tamaulipas", "tanker-wreck", "anom-10", "video"]
  },
  {
    "sourceId": "NOAA-ANOM-11-SS-BLUEFIELDS",
    "name": "SS Bluefields (Freighter wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-07-15",
    "latitude": 34.76211,
    "longitude": -75.50496,
    "depthMeters": 228.6,
    "quantity": 1,
    "description": "ANOM-11: SS Bluefields. Freighter wreck at ~750 ft depth (NOAA-published site). Sonar evidence: Side-scan + high-resolution multibeam.",
    "sourceOrganization": "NOAA Monitor National Marine Sanctuary",
    "sourceUrl": "https://monitor.noaa.gov/shipwrecks/bluefields.html",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["ss-bluefields", "freighter-wreck", "anom-11", "high-resolution-multibeam"]
  },
  {
    "sourceId": "NOAA-ANOM-12-UNKNOWN-TRAWLER",
    "name": "Unknown fishing trawler (Trawler wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1978,
    "eventDate": "1978-08-20",
    "latitude": 42.33500,
    "longitude": -70.31500,
    "depthMeters": 32.5,
    "quantity": 1,
    "description": "ANOM-12: Unknown fishing trawler. Trawler wreck at Stellwagen Bank, 105–110 ft depth. Sonar evidence: Side-scan + multibeam.",
    "sourceOrganization": "NOAA Stellwagen Bank National Marine Sanctuary",
    "sourceUrl": "https://stellwagen.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["unknown-trawler", "trawler-wreck", "anom-12", "stellwagen-bank"]
  },
  {
    "sourceId": "NOAA-ANOM-13-EDNA-G",
    "name": "Edna G (Fishing vessel wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1972,
    "eventDate": "1972-06-30",
    "latitude": 42.36800,
    "longitude": -70.34200,
    "depthMeters": 91.4,
    "quantity": 1,
    "description": "ANOM-13: Edna G. Fishing vessel wreck at Stellwagen Bank, >300 ft depth. Sonar evidence: Side-scan + ROV.",
    "sourceOrganization": "NOAA Stellwagen Bank National Marine Sanctuary",
    "sourceUrl": "https://stellwagen.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["edna-g", "fishing-vessel-wreck", "anom-13", "rov"]
  },
  {
    "sourceId": "NOAA-ANOM-14-MYSTERY-COLLIER",
    "name": "Mystery Collier (Wooden schooner wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1902,
    "eventDate": "1902-11-12",
    "latitude": 42.41500,
    "longitude": -70.38500,
    "depthMeters": 122.0,
    "quantity": 1,
    "description": "ANOM-14: Mystery Collier. Wooden schooner wreck at Stellwagen Bank, >400 ft depth. Sonar evidence: Side-scan + ROV.",
    "sourceOrganization": "NOAA Stellwagen Bank National Marine Sanctuary",
    "sourceUrl": "https://stellwagen.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["mystery-collier", "wooden-schooner-wreck", "anom-14", "rov"]
  },
  {
    "sourceId": "NOAA-ANOM-15-UNCHARTERED-OBSTRUCTION",
    "name": "Uncharted obstruction / possible wreckage (Seafloor obstruction)",
    "type": "OTHER",
    "eventYear": 2019,
    "eventDate": "2019-09-18",
    "latitude": 37.83300,
    "longitude": -75.20900,
    "depthMeters": 14.3,
    "quantity": 1,
    "description": "ANOM-15: Uncharted obstruction / possible wreckage. Seafloor obstruction at ~47 ft depth. Sonar evidence: Side-scan sonar.",
    "sourceOrganization": "NOAA Office of Coast Survey",
    "sourceUrl": "https://nauticalcharts.noaa.gov/",
    "coordinateAccuracy": "APPROXIMATE",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["uncharted-obstruction", "seafloor-obstruction", "anom-15", "navigation-hazard"]
  },
  {
    "sourceId": "NOAA-ANOM-16-HEROIC",
    "name": "Heroic (Fishing vessel / former minesweeper wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1969,
    "eventDate": "1969-05-22",
    "latitude": 42.37260,
    "longitude": -70.36982,
    "depthMeters": 30.5,
    "quantity": 1,
    "description": "ANOM-16: Heroic. Fishing vessel / former minesweeper wreck at ~100 ft depth. Sonar evidence: Side-scan/underwater survey; large engine, hull fragments, trawl winch, anchor and chain.",
    "sourceOrganization": "NOAA Stellwagen Bank National Marine Sanctuary",
    "sourceUrl": "https://stellwagen.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["heroic", "minesweeper-wreck", "anom-16", "side-scan"]
  },
  {
    "sourceId": "NOAA-ANOM-17-PATRIOT",
    "name": "Patriot (Steel fishing vessel wreck)",
    "type": "SHIPWRECK",
    "eventYear": 2009,
    "eventDate": "2009-01-03",
    "latitude": 42.40427,
    "longitude": -70.45328,
    "depthMeters": 30.5,
    "quantity": 1,
    "description": "ANOM-17: Patriot. Steel fishing vessel wreck at ~100 ft depth. Sonar evidence: Wreck target lying on starboard side; fishing-net/gear hazards.",
    "sourceOrganization": "NOAA Stellwagen Bank National Marine Sanctuary",
    "sourceUrl": "https://stellwagen.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["patriot", "steel-fishing-vessel-wreck", "anom-17", "net-hazards"]
  },
  {
    "sourceId": "NOAA-ANOM-18-JOSEPHINE-MARIE",
    "name": "Josephine Marie (Steel stern trawler wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1992,
    "eventDate": "1992-02-01",
    "latitude": 42.18208,
    "longitude": -70.22443,
    "depthMeters": 32.0,
    "quantity": 1,
    "description": "ANOM-18: Josephine Marie. Steel stern trawler wreck at 105 ft depth. Sonar evidence: Side-scan sonar image; inverted wreck with machinery and fishing gear.",
    "sourceOrganization": "NOAA Stellwagen Bank National Marine Sanctuary",
    "sourceUrl": "https://stellwagen.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["josephine-marie", "steel-stern-trawler", "anom-18", "side-scan"]
  },
  {
    "sourceId": "NOAA-ANOM-19-UNIDENTIFIED-TRAWLER",
    "name": "Unidentified Trawler (Unknown steel trawler)",
    "type": "SHIPWRECK",
    "eventYear": 1985,
    "eventDate": "1985-07-14",
    "latitude": 42.31218,
    "longitude": -70.29738,
    "depthMeters": 32.8,
    "quantity": 1,
    "description": "ANOM-19: Unidentified Trawler. Unknown steel trawler at 105–110 ft depth. Sonar evidence: Side-scan shows wreck broken into major sections; multibeam confirms structure.",
    "sourceOrganization": "NOAA Stellwagen Bank National Marine Sanctuary",
    "sourceUrl": "https://stellwagen.noaa.gov/maritime/",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["unidentified-trawler", "unknown-steel-trawler", "anom-19", "broken-sections"]
  },
  {
    "sourceId": "NOAA-ANOM-20-BLUEFIELDS",
    "name": "Bluefields (WWII freighter wreck)",
    "type": "SHIPWRECK",
    "eventYear": 1942,
    "eventDate": "1942-07-15",
    "latitude": 34.76211,
    "longitude": -75.50496,
    "depthMeters": 228.6,
    "quantity": 1,
    "description": "ANOM-20: Bluefields. WWII freighter wreck at 750 ft depth. Sonar evidence: Side-scan + high-resolution multibeam; largely intact steel hull with fallen masts/cargo booms.",
    "sourceOrganization": "NOAA Monitor National Marine Sanctuary",
    "sourceUrl": "https://monitor.noaa.gov/shipwrecks/bluefields.html",
    "coordinateAccuracy": "EXACT",
    "dataStatus": "HISTORICAL_REFERENCE",
    "tags": ["bluefields", "wwii-freighter-wreck", "anom-20", "intact-hull"]
  }
] as const;

