import { connect, disconnect, model } from 'mongoose';
import { HistoricalReference, HistoricalReferenceSchema } from '../modules/historical/schemas/historical-reference.schema';

const records = [
  {
    sourceId: 'NOAA-TITANIC-2004-EXPEDITION',
    name: 'RMS Titanic wreck reference',
    type: 'SHIPWRECK',
    eventYear: 2004,
    eventDate: '2004-05-27',
    latitude: 41.7325,
    longitude: -49.94695,
    depthMeters: null,
    quantity: 1,
    description: 'NOAA NCEI archive records the 2004 Titanic expedition area at 41.7325 N, 49.94695 W.',
    sourceOrganization: 'NOAA National Centers for Environmental Information',
    sourceUrl: 'https://www.ncei.noaa.gov/archive/archive-management-system/OAS/bin/prd/jquery/accession/details/72311/3',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['titanic', 'wreck', 'north-atlantic'],
  },
  {
    sourceId: 'NOAA-ATLAS-MONITOR-1942',
    name: 'Atlas wreck',
    type: 'SHIPWRECK',
    eventYear: 1942,
    eventDate: '1942-04-09',
    latitude: 34.52834,
    longitude: -76.24206,
    depthMeters: 38.1,
    quantity: 1,
    description: 'NOAA Monitor National Marine Sanctuary reference: tanker Atlas, lost April 9, 1942.',
    sourceOrganization: 'NOAA Monitor National Marine Sanctuary',
    sourceUrl: 'https://monitor.noaa.gov/shipwrecks/atlas.html',
    coordinateAccuracy: 'EXACT',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['atlas', 'wreck', 'tanker'],
  },
  {
    sourceId: 'NOAA-MANOOA-CONTAINERS-2015',
    name: 'M/V Manoa lost containers',
    type: 'CONTAINER',
    eventYear: 2015,
    eventDate: '2015-12-14',
    latitude: 37.72,
    longitude: -122.65,
    depthMeters: null,
    quantity: 12,
    description: 'NOAA IncidentNews reports 12 containers believed lost about 8 miles outside the Golden Gate.',
    sourceOrganization: 'NOAA IncidentNews / USCG report',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/9206',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['manoa', 'containers', 'marine-debris'],
  },
  {
    sourceId: 'NOAA-ONEAPUS-CONTAINERS-2020',
    name: 'ONE Apus container-loss incident',
    type: 'CONTAINER',
    eventYear: 2020,
    eventDate: '2020-11-30',
    latitude: 33.23,
    longitude: -172.548333,
    depthMeters: null,
    quantity: 1900,
    description: 'NOAA reports a container collapse/loss incident in the North Pacific; reported losses could exceed 1,900 containers.',
    sourceOrganization: 'NOAA IncidentNews',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10208',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['one-apus', 'containers', 'north-pacific'],
  },
  {
    sourceId: 'NOAA-MAERSKESSEN-CONTAINERS-2021',
    name: 'M/V Maersk Essen container-loss incident',
    type: 'CONTAINER',
    eventYear: 2021,
    eventDate: '2021-01-16',
    latitude: 28.411667,
    longitude: -154.126667,
    depthMeters: null,
    quantity: 732,
    description: 'NOAA reports an estimated 732 40-foot containers lost at the reported position north of Oahu.',
    sourceOrganization: 'NOAA IncidentNews',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10221',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['maersk-essen', 'containers', 'north-pacific'],
  },
  {
    sourceId: 'NOAA-CONTAINER-SHIP-WASHINGTON-2021',
    name: 'Washington Coast container-loss incident',
    type: 'CONTAINER',
    eventYear: 2021,
    eventDate: '2021-10-21',
    latitude: 48.3385,
    longitude: -123.360667,
    depthMeters: null,
    quantity: 110,
    description: 'NOAA reports approximately 110 containers associated with a container ship incident west of the Strait of Juan de Fuca.',
    sourceOrganization: 'NOAA IncidentNews',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10374',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['washington', 'containers', 'juan-de-fuca'],
  },
  {
    sourceId: 'NOAA-PRESIDENT-EISENHOWER-CONTAINERS-2024',
    name: 'M/V President Eisenhower lost containers',
    type: 'CONTAINER',
    eventYear: 2024,
    eventDate: '2024-02-07',
    latitude: 36.283333,
    longitude: -122.973333,
    depthMeters: null,
    quantity: 24,
    description: 'NOAA reports 24 containers lost offshore of Monterey; coordinates are approximate and refer to the incident location.',
    sourceOrganization: 'NOAA IncidentNews',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10740',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['president-eisenhower', 'containers', 'monterey'],
  },
  {
    sourceId: 'NOAA-SM-PORTLAND-CONTAINERS-2025',
    name: 'C/V S.M. Portland lost containers',
    type: 'CONTAINER',
    eventYear: 2025,
    eventDate: '2025-03-04',
    latitude: 53.37,
    longitude: 175.98,
    depthMeters: null,
    quantity: 81,
    description: 'NOAA reports 81 containers lost approximately 30 miles north of Buldir Island. NOAA supplied longitude as 184°01.20′ W; the globe stores the normalized equivalent +175.98° E.',
    sourceOrganization: 'NOAA IncidentNews',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10930',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    normalizedLongitudeNote: '184°01.20′ W is normalized to +175.98° E for GeoJSON/Cesium longitude range.',
    tags: ['sm-portland', 'containers', 'aleutian-islands'],
  },
  {
    sourceId: 'NOAA-STYROFOAM-FORT-FUNSTON-2021',
    name: 'Fort Funston marine debris observation',
    type: 'MARINE_DEBRIS',
    eventYear: 2021,
    eventDate: '2021-01-27',
    latitude: 37.72,
    longitude: -122.506833,
    depthMeters: null,
    quantity: null,
    description: 'NOAA IncidentNews documents Styrofoam debris observed near Fort Funston; this is a shoreline debris reference, not a sonar detection.',
    sourceOrganization: 'NOAA IncidentNews',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10225',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['styrofoam', 'fort-funston', 'marine-debris'],
  },
  {
    sourceId: 'NOAA-MAERSK-ESSEN-2021',
    name: 'M/V Maersk Essen lost containers',
    type: 'CONTAINER',
    eventYear: 2021,
    eventDate: '2021-01-16',
    latitude: 28.411667,
    longitude: -154.126667,
    depthMeters: null,
    quantity: 732,
    description: 'Approximate incident position for an estimated 732 lost 40-foot containers.',
    sourceOrganization: 'NOAA IncidentNews / USCG',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10221',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['2021', 'containers', 'marine-debris', 'maersk-essen'],
  },
  {
    sourceId: 'NOAA-WASHINGTON-CONTAINERS-2021',
    name: 'Washington Coast container-loss incident',
    type: 'CONTAINER',
    eventYear: 2021,
    eventDate: '2021-10-21',
    latitude: 48.3385,
    longitude: -123.360667,
    depthMeters: null,
    quantity: 110,
    description: 'NOAA incident reference for approximately 110 containers reported overboard.',
    sourceOrganization: 'NOAA IncidentNews / USCG',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10374',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['2021', 'containers', 'marine-debris'],
  },
  {
    sourceId: 'NOAA-TOURIST2-2022',
    name: 'M/V Tourist No. 2 partially sunk',
    type: 'SHIPWRECK',
    eventYear: 2022,
    eventDate: '2022-07-28',
    latitude: 46.192,
    longitude: -123.836667,
    depthMeters: null,
    quantity: 1,
    description: 'Partially sunk 1924 former car ferry and derelict vessel reference in Astoria.',
    sourceOrganization: 'NOAA IncidentNews / USCG',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10496',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['2022', 'shipwreck', 'derelict-vessel'],
  },
  {
    sourceId: 'NOAA-MATADOR-2023',
    name: 'F/V Matador sunken vessel',
    type: 'SHIPWRECK',
    eventYear: 2023,
    eventDate: '2023-02-08',
    latitude: 33.845833,
    longitude: -118.415,
    depthMeters: 51.8,
    quantity: 1,
    description: '43-foot fishing vessel reported sunk about one-third mile offshore of Redondo Beach.',
    sourceOrganization: 'NOAA IncidentNews / USCG',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10567',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['2023', 'shipwreck', 'sunken-vessel'],
  },
  {
    sourceId: 'NOAA-MAZAPETA-2023',
    name: 'Tug MAZAPETA sunken vessel',
    type: 'SHIPWRECK',
    eventYear: 2023,
    eventDate: '2023-09-04',
    latitude: 38.057333,
    longitude: -121.501,
    depthMeters: null,
    quantity: 1,
    description: 'Sunken tug reference in Little Potato Slough, Stockton, California.',
    sourceOrganization: 'NOAA IncidentNews / USCG',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10669',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['2023', 'shipwreck', 'derelict-vessel'],
  },
  {
    sourceId: 'NOAA-PRESIDENT-EISENHOWER-2024',
    name: 'M/V President Eisenhower lost containers',
    type: 'CONTAINER',
    eventYear: 2024,
    eventDate: '2024-02-07',
    latitude: 36.283333,
    longitude: -122.973333,
    depthMeters: null,
    quantity: 24,
    description: 'NOAA reported 24 containers lost offshore of Monterey; coordinates are approximate incident coordinates.',
    sourceOrganization: 'NOAA IncidentNews / USCG',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10740',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['2024', 'containers', 'marine-debris'],
  },
  {
    sourceId: 'NOAA-DALI-2024',
    name: 'DALI / Key Bridge marine-casualty reference',
    type: 'MARINE_DEBRIS',
    eventYear: 2024,
    eventDate: '2024-03-26',
    latitude: 39.270333,
    longitude: -76.574667,
    depthMeters: null,
    quantity: null,
    description: 'NOAA incident reference notes containers fell into the water after the vessel struck the Francis Scott Key Bridge.',
    sourceOrganization: 'NOAA IncidentNews / USCG',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10761',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['2024', 'marine-debris', 'containers', 'casualty'],
  },
  {
    sourceId: 'NOAA-SM-PORTLAND-2025',
    name: 'C/V S.M. Portland lost containers',
    type: 'CONTAINER',
    eventYear: 2025,
    eventDate: '2025-03-04',
    latitude: 53.37,
    longitude: 175.98,
    depthMeters: null,
    quantity: 81,
    description: 'NOAA reported 81 containers lost approximately 30 miles north of Buldir Island; incident longitude normalized for globe display.',
    sourceOrganization: 'NOAA IncidentNews / USCG',
    sourceUrl: 'https://incidentnews.noaa.gov/incident/10930',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['2025', 'containers', 'marine-debris'],
  },
  {
    sourceId: 'NOAA-FISHING-GEAR-REFERENCE',
    name: 'Derelict fishing gear / ghost-net evidence reference',
    type: 'FISHING_GEAR',
    eventYear: 2022,
    eventDate: '2022-01-01',
    latitude: 46.5,
    longitude: -87.0,
    depthMeters: null,
    quantity: null,
    description: 'Regional reference point for the Upper Great Lakes ghost-net removal program. The source describes an ongoing hazard but does not publish a single sonar target coordinate; this point is a regional reference only.',
    sourceOrganization: 'NOAA Marine Debris Program',
    sourceUrl: 'https://marinedebris.noaa.gov/removal/increasing-efficiency-locating-and-removing-ghost-nets-upper-great-lakes',
    coordinateAccuracy: 'APPROXIMATE',
    dataStatus: 'HISTORICAL_REFERENCE',
    tags: ['ghost-net', 'fishing-gear', 'regional-reference'],
  }
]

async function main() {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/marinevision';
  await connect(uri);
  const HistoricalModel = model(HistoricalReference.name, HistoricalReferenceSchema, 'historical_references');
  const ops = records.map((r) => ({
    updateOne: { filter: { sourceId: r!.sourceId }, update: { $set: r! }, upsert: true },
  }));
  const result = await HistoricalModel.bulkWrite(ops);
  console.log(`Historical reference seed complete: upserted=${result.upsertedCount}, modified=${result.modifiedCount}`);
  await disconnect();
}

main().catch(async (err) => {
  console.error(err);
  await disconnect();
  process.exit(1);
});
